### ISSUE TITLE
warn users on edit-config if name has strange characters.

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaqd-control#4]
Give users a notice if e.g. dash/space is in the device name

**Comment by ksunden** [comment]
yaq itself is actually mostly fine with any string, but we may wish to specify a lowest common denominator so we work well with things like happi which expect names to be valid (python or otherwise) identifiers following some regex e.g. `[a-zA-z_][a-zA-z0-9_]*` (python is a bit broader, allowing "letterlike" unicode characters, but such a regex may guarantee interoperability with a wider array of other tools.
